---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-echo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:latest
        args: 
          - -text=hello-world
        ports:
        - name: http
          containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: default
spec:
  ports:
  - port: 5678
    targetPort: 5678
  selector:
    app: http-echo
