---
- name: Playbook for Kubernetes master
  hosts: all
  become: yes

  tasks:

  - name: Configure Kubernetes
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_addr }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes master
    command: kubeadm init --apiserver-advertise-address={{ node_addr }} --apiserver-cert-extra-sans={{ node_addr }}  --node-name=kube-master-1 --pod-network-cidr=192.168.0.0/16

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    loop:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - echo "source <(kubectl completion bash)" >> /home/vagrant/.bashrc
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Deploy calico network plugin
    become: false
    command: kubectl create -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
